  version: '3.7'

  services:
    backend_auth:
      image: spoonlab/ourjourney-be-auth:latest
      container_name: backend_auth
      environment:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ourjourney_auth_db
        MYSQL_USER: root
      env_file:
        - .env
      volumes:
        - static_volume:/home/our_journey/static
      ports:
        - "8000:8000"
      networks:
        - my_network

    nginx:
        image: nginx:latest
        ports:
          - "80:80"
        volumes:
          - static_volume:/home/our_journey/static
          - /home/ubuntu/nginx.conf:/etc/nginx/nginx.conf # 로컬 nginx.conf 파일을 컨테이너 내부로 마운트, 로컬 파일 절대 경로로 수정
        depends_on:
          - backend_auth # 웹 서비스와 의존 관계
        networks:
          - my_network

  networks:
    my_network:
      driver: bridge

  volumes:
    static_volume: