# Generated by Django 4.2 on 2024-09-08 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0002_user_email_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email_verified",
        ),
    ]
