# Generated by Django 4.2 on 2024-09-11 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0004_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
    ]
