# Generated by Django 4.2 on 2024-09-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0006_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nick_name", models.CharField(max_length=100, null=True)),
                ("img_url", models.CharField(max_length=200, null=True)),
                ("user_id", models.BigIntegerField()),
                ("self_introduction", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(default=None, null=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
            ],
            options={
                "db_table": "profile",
                "managed": False,
            },
        ),
    ]
